# .travis.yml
language: php

php:
    - 5.3
    - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - COMPOSER_ROOT_VERSION=dev-master php composer.phar --dev install
  - src/ByExample/DemoBundle/Resources/bin/validate.sh

script: phpunit -c app/

notifications:
  email: "sdiaz@symfony.tv"
